name: 'fish-shop/install-plugin-manager'
description: 'A GitHub action for installing a fish shell plugin manager'
branding:
  icon: 'arrow-down'
  color: 'blue'
inputs:
  plugin-manager:
    description: 'The name of the fish shell plugin manager to install'
runs:
  using: "composite"
  steps:
    - run: |
        set -gx TERM xterm-256color

        switch ${{ inputs.plugin-manager }}
            case fisher
                curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
            case oh-my-fish
                curl -L https://get.oh-my.fish > omf-install
                chmod u+x omf-install
                ./omf-install -y --noninteractive
            case plug.fish
                curl -sSL https://git.io/fish-plug | source && plug install kidonng/fish-plug
        end
      shell: fish {0}
